apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: kafka-producer
  namespace: kamel-demo
spec:
  configuration:
  - type: configmap
    value: appconfig
  resources:
  - content: |
      ---
      openapi: 3.0.2
      info:
        title: Camel K Object API
        version: 1.0.0
        description: A CRUD API for an object store
      paths:
        /v1:
          get:
            responses:
              "200":
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        type: string
                description: Object list
            operationId: list
            summary: List the objects
        /v1/{name}:
          get:
            responses:
              "200":
                content:
                  application/octet-stream: {}
                description: The object content
            operationId: get
            summary: Get the content of an object
          put:
            requestBody:
              description: The object content
              content:
                application/octet-stream: {}
              required: true
            responses:
              "200":
                description: The object has been created
            operationId: create
            summary: Save an object
          delete:
            responses:
              "204":
                description: Object has been deleted
            operationId: delete
            summary: Delete an object
          parameters:
          - name: name
            description: Name of the object
            schema:
              type: string
            in: path
            required: true
    name: openapi.yaml
    type: openapi
  sources:
  - content: |+
      import org.apache.camel.builder.RouteBuilder;


      public class KafkaProducer extends RouteBuilder {
        @Override
        public void configure() throws Exception {
              from("direct:create")
              .id("generator")
              .convertBodyTo(String.class)
              .to("kafka:{{kafka.topic}}?brokers={{kafka.bootstrap-servers}}");
       }
      }



    name: KafkaProducer.java
