apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: server
    app.kubernetes.io/name: messagedb
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: messagedb
    app.kubernetes.io/part-of: demo-app
  name: messagedb
stringData:
  database-name: messagedb
  database-password: Demo1234
  database-root-password: Demo1234
  database-user: messagedb
  
